### ISSUE TITLE
'module' object has no attribute 'checkLink'

### ISSUE THREAD

**Issue by FlashLightNing** [JeffreyWei/xunleiaccount#2]
我在运行python xunlei.py的时候报这个错是为什么？

Traceback (most recent call last):
  File "xunlei.py", line 55, in <module>
    data = getXunLeiAccount()
  File "xunlei.py", line 21, in getXunLeiAccount
    if (utils.checkLink(link.get("title")) >= 0):
AttributeError: 'module' object has no attribute 'checkLink'

**Comment by JeffreyWei** [comment]
文件的第5行引进引入了，checkLink定义在utils.py这个文件
